### ISSUE TITLE
Error to sniff .GlobalPreferences.plist

### ISSUE THREAD

**Issue by 9840380** [zcutlip/prefsniff#3]
hi 
try to sniff  prefsniff /Users/z/Library/Preferences/.GlobalPreferences.plist
Mac os Catalina 10.15.7
PREFSNIFF version 0.1.0b3

give me error

```
PREFSNIFF version 0.1.0b3
Watching prefs file: /Users/z/Library/Preferences/.GlobalPreferences.plist
Traceback (most recent call last):
  File "/usr/local/bin/prefsniff", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/prefsniff/prefsniff_main.py", line 7, in main
    prefsniff_main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/prefsniff/prefsniff.py", line 658, in main
    diffs = PrefSniff(plistpath)
  File "/Library/Python/2.7/site-packages/prefsniff/prefsniff.py", line 322, in __init__
    pref1 = deserialize_plist(f.read())
  File "/Library/Python/2.7/site-packages/prefsniff/prefsniff.py", line 60, in deserialize_plist
    return plistlib.readPlistFromString(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 103, in readPlistFromString
    return readPlist(StringIO(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 247, column 19
```

**Comment by zcutlip** [comment]
It looks like you're using python2.7, which isn't supported, and also a really old version of prefsniff

Please update preffsniff to the latest release and run with a supported python version. 

Let me know if that gets you going

**Comment by 9840380** [comment]
```
~/Library/Preferences$ prefsniff "/Users/z/Library/Preferences/.GlobalPreferences.plist"
PREFSNIFF version 0.2.2
Watching prefs file: /Users/z/Library/Preferences/.GlobalPreferences.plist
Traceback (most recent call last):
  File "/usr/local/bin/prefsniff", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefsniff/prefsniff.py", line 508, in main
    diffs = PrefSniff(plistpath, plistpath2=plist2)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefsniff/prefsniff.py", line 178, in __init__
    self.diff = self._unified_diff(pref1, pref2, plistpath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefsniff/prefsniff.py", line 214, in _unified_diff
    fromxml = plistlib.dumps(
              ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 910, in dumps
    dump(value, fp, fmt=fmt, skipkeys=skipkeys, sort_keys=sort_keys)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 903, in dump
    writer.write(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 334, in write
    self.write_value(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 357, in write_value
    self.write_dict(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 398, in write_dict
    self.write_value(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 366, in write_value
    self.write_array(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 408, in write_array
    self.write_value(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 357, in write_value
    self.write_dict(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 398, in write_dict
    self.write_value(value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 339, in write_value
    self.simple_element("string", value)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 303, in simple_element
    value = _escape(value)
            ^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/plistlib.py", line 164, in _escape
    raise ValueError("strings can't contain control characters; "
ValueError: strings can't contain control characters; use bytes instead
```

**Comment by zcutlip** [comment]
hmm, I don't suppose you'd be able to share your .GlobalPreferences.plist? If so please zip it up before uploading so it doesn't accidentally get mangled

I'm curious how it's getting control characters in it

**Comment by 9840380** [comment]
This is my .GlobalPreferences
(link deleted)

**Comment by zcutlip** [comment]
I downloaded your preferences file and can reproduce the problem. Feel free to delete it now if you don't want it to remain public

I believe the issue is with the `--------^T^T^T^T^T^T^T^T^U^U🔻 Start` in your text replacements.

I want to see if I can figure out a way to handle that gracefully; `plistlib` does not like it.

It would help if I could add that text replacement to my own settings so I can experiment, but I can't figure out how to enter it into system settings.

How did you get it in there to start with?

**Comment by zcutlip** [comment]
actually, I'm going to go ahead and delete your dropbox link from the comment so no one else will be able to access it

**Comment by johnsonea** [comment]
Same "strings can't contain control characters" error on ~/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist due to an ESC character in NSUserKeyEquivalents (where ESC separates parts of menu/submenu/submenu ... for example, I have a key equivalent set up for Message -> Move to -> SomeMailbox, which is coded in NSUserKeyEquivalents as <key>ESCMessageESCMove toESCSomeMailbox</key>.)

**Comment by zcutlip** [comment]
Sorry for taking so long on this. I'll try to revisit the issue as soon as I can

I suspect the best I'll be able to do is detect the issue and fail gracefully, so it least it doesn't blow up on you.

The problem is `prefsniff` depends on being able to work with the XML representation of the plist. When you have a string with escape sequences like this, `plistlib` raises an exception because those bytes can't be encoded into valid XML.

At the moment I don't know if a work-around. But I definitely want `prefsniff` to gracefully inform you of the problem at the very list.

**Comment by zcutlip** [comment]
> Same "strings can't contain control characters" error on ~/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist due to an ESC character in NSUserKeyEquivalents (where ESC separates parts of menu/submenu/submenu ... for example, I have a key equivalent set up for Message -> Move to -> SomeMailbox, which is coded in NSUserKeyEquivalents as ESCMessageESCMove toESCSomeMailbox.)

This additional context is really helpful, thank you. Again not sure at this point if there's a solution, but I'll see what I can do

Were you able to set up that up through the GUI, or was this via some other method like `defaults`, etc?

**Comment by johnsonea** [comment]
> > for example, I have a key equivalent set up for Message -> Move to -> SomeMailbox, which is coded in NSUserKeyEquivalents as ESCMessageESCMove toESCSomeMailbox.)
> 
> Were you able to set up that up through the GUI, or was this via some other method like `defaults`, etc?

Can be created either way. Via the GUI, it’s set up as Message->Move to->SomeMailbox; via `defaults` it is done with `defaults … ‘\033Message\033Move to\033SomeMailbox’`. Either way, it ends up in the .plist as `ESCMessageESCMove toESCSomeMailbox`.

**Comment by zcutlip** [comment]
Awesome thanks. I'll play with it on my end some
